apiVersion: v1
kind: Pod
metadata:
  name: sudsundaysample-pod34
  namespace: testing
  labels:
    selector: sample-pod  # This ensures correct pod selection by PodMover
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
